### PR TITLE
feat: Update template with new splash screen

### PR DESCRIPTION
**Pull request by edassis**
Hi,

I updated the export-godot_v4.3.html file with the new upstream html template. We have a pretty splash screen now.

I will be looking to isolate the Scorm logic into a separate script file to decouple it and increase the compatibility.

### CODE REVIEW

**Comment by EsdrasCaleb** [comment]
HI thx for your contribution. How you plan to isolate the scorm logic?

**Comment by edassis** [comment]
Instead of maintaining a custom .html for the plugin, I decided to follow a different approach: Patch the generated .html file after the export process (`_export_end()`). I already did this on my fork. I took the opportunity to add the option to generate a .zip of the exported files and, I isolated the SCORM logic into a separate .js file (`scorm.js`).

I'm just finalizing some minor adjustments that I planned, you can check out my work here: https://github.com/EsdrasCaleb/godot_scormplugin/compare/main...edassis:godot_scormplugin:refactor/separate_files

Let me know what you think. I plan to open a PR in the next week.

**Comment by EsdrasCaleb** [comment]
wow that is awesome. I don't know if the Godot page suport co author but i can put you as a mantainer in this repository if you want. I do not have time to maintain and my PHD project shifted from this and I will need to work with automated tests now. Do you want be a maintainer?

**Comment by edassis** [comment]
Yeah, I will be more than happy on helping you maintain this project. I have a side project originally created on Unity that I'm trying to port to Godot, and the Scorm support was something that was holding me back. Thanks!

Good luck with your PhD.

**Pull request merged**
